apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-db
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/moabdelazem/My_ArgoCD_Applications.git
    targetRevision: main
    path: manifests/backstage
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    retry: { limit: 5, backoff: { duration: 10s, factor: 2, maxDuration: 2m } }
    syncOptions: [ CreateNamespace=true ]