apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"      # runs only after the operator is Healthy
spec:
  project: default
  source:
    repoURL: https://github.com/moabdelazem/My_ArgoCD_Applications.git
    targetRevision: main
    path: manifests/database
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    retry:
      limit: 5                    
      backoff: { duration: 10s, factor: 2, maxDuration: 2m }
    syncOptions:
      - CreateNamespace=true