apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"     # before cnpg-operator (0) and cnpg-cluster (1)
spec:
  project: default
  source:
    repoURL: https://github.com/rancher/local-path-provisioner.git
    targetRevision: v0.0.37
    path: deploy/chart/local-path-provisioner
    helm:
      values: |
        storageClass:
          defaultClass: true               # sets local-path as the default SC
  destination:
    server: https://kubernetes.default.svc
    namespace: local-path-storage
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions:
      - CreateNamespace=true